BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `TIPO_CLIENTE` (
	`TPC_ID_TIPO_CLIENTE`	INTEGER ( 1 ) NOT NULL UNIQUE,
	`TPC_DS_ALIAS`	TEXT ( 15 ) NOT NULL UNIQUE,
	PRIMARY KEY(`TPC_ID_TIPO_CLIENTE`)
);
CREATE TABLE IF NOT EXISTS `CLIENTE_MENSALISTA` (
	`CLM_ID_MATRICULA`	INTEGER NOT NULL UNIQUE,
	`CLM_DS_CPF`	TEXT ( 11 ) NOT NULL UNIQUE,
	`CLM_DS_NOME`	TEXT ( 60 ) NOT NULL,
	`CLM_DT_NASCIMENTO`	DATE NOT NULL,
	PRIMARY KEY(`CLM_ID_MATRICULA`)
);
CREATE TABLE IF NOT EXISTS `VEICULO` (
	`VCL_ID_PLACA`	INTEGER ( 7 ) NOT NULL UNIQUE,
	`VCL_FK_PROPRIETARIO`	INTEGER NOT NULL,
	`VCL_DS_MODELO`	TEXT NOT NULL,
	`VCL_DS_COR`	TEXT NOT NULL,
	PRIMARY KEY(`VCL_ID_PLACA`),
	FOREIGN KEY(`VCL_FK_PROPRIETARIO`) REFERENCES `CLIENTE_MENSALISTA`(`CLM_ID_MATRICULA`)
);
CREATE TABLE IF NOT EXISTS `VALOR` (
    `VAL_ID_VALOR` INT NOT NULL AUTOINCREMENT,
	`VAL_FK_TIPO_CLIENTE`	INTEGER ( 1 ) NOT NULL,
	`VAL_VL_VALOR`	REAL NOT NULL,
    PRIMARY KEY(`VAL_ID_VALOR`),
	FOREIGN KEY(`VAL_FK_TIPO_CLIENTE`) REFERENCES `TIPO_CLIENTE`(`TPC_ID_TIPO_CLIENTE`)
);
CREATE TABLE IF NOT EXISTS `VAGA` (
	`VAG_ID_VAGA`	INTEGER NOT NULL UNIQUE,
	`VAG_ST_SITUACAO`	INTEGER ( 1 ) NOT NULL DEFAULT 0,
	`VAG_FK_TIPO_CLIENTE`	INTEGER ( 1 ) NOT NULL,
	FOREIGN KEY(`VAG_FK_TIPO_CLIENTE`) REFERENCES `TIPO_CLIENTE`(`TPC_ID_TIPO_CLIENTE`),
	PRIMARY KEY(`VAG_ID_VAGA`)
);
CREATE TABLE IF NOT EXISTS `CONTRATO` (
	`CNT_ID_NUMERO`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`CNT_FK_CLIENTE`	INTEGER NOT NULL UNIQUE,
	`CNT_DT_CRIACAO`	DATE NOT NULL,
	`CNT_DT_RENOVACAO`	DATE DEFAULT NULL,
	`CNT_ST_SITUACAO`	INTEGER ( 1 ) NOT NULL,
	FOREIGN KEY(`CNT_FK_CLIENTE`) REFERENCES `CLIENTE_MENSALISTA`(`CLM_ID_MATRICULA`)
);
CREATE TABLE IF NOT EXISTS `BOLETO_CONTRATO` (
	`BLC_ID_NUMERO`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`BLC_VL_VALOR`	REAL NOT NULL,
	`BLC_DT_VENCIMENTO`	DATE NOT NULL,
	`BLC_FK_NUMERO_CONTRATO`	INTEGER NOT NULL,
	FOREIGN KEY(`BLC_FK_NUMERO_CONTRATO`) REFERENCES `CONTRATO`(`CNT_ID_NUMERO`)
);
CREATE TABLE IF NOT EXISTS `VOUCHER` (
	`VCH_ID_VOUCHER`	TEXT ( 5 ) NOT NULL UNIQUE,
	`VCH_FK_PLACA`	TEXT ( 7 ) NOT NULL,
	`VCH_FK_TIPO_CLIENTE`	INTEGER ( 1 ) NOT NULL,
	`VCH_FK_VAGA`	INTEGER NOT NULL,
	`VCH_HR_ENTRADA`	DATETIME NOT NULL,
	`VCH_HR_SAIDA`	DATETIME DEFAULT NULL,
	FOREIGN KEY(`VCH_FK_TIPO_CLIENTE`) REFERENCES `TIPO_CLIENTE`(`TPC_ID_TIPO_CLIENTE`),
	FOREIGN KEY(`VCH_FK_VAGA`) REFERENCES `VAGA`(`VAG_ID_VAGA`),
	FOREIGN KEY(`VCH_FK_PLACA`) REFERENCES `VEICULO`(`VCL_ID_PLACA`),
	PRIMARY KEY(`VCH_ID_VOUCHER`)
);
COMMIT;
